name: test
on:
  push:
    branches:
    - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      ocaml-compiler: 4.14.1
    - uses: actions/checkout@v3
    - run: opam install -y dune ocamlformat
    - run: opam exec -- dune fmt

  build-and-run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [ 4.14.1, 4.13.0 ]
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - if: matrix.os == 'ubuntu-latest'
      name: 'Run "apt update" so setup-ocaml can install depexts (ubuntu)'
      run: |
        sudo apt update
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest

  test-packaging-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [ 4.14.1, 4.13.0 ]
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: 'Vendor Rust Dependencies'
      run: scripts/switch-to-vendored-rust.sh
    - name: 'Create release artifact'
      run: |
        tar -czf /tmp/llama.tar.gz --exclude=.git -C .. llama
        mkdir /tmp/empty
        cd /tmp/empty
    - if: matrix.os == 'ubuntu-latest'
      name: 'Run "apt update" so setup-ocaml can install depexts (ubuntu)'
      run: |
        sudo apt update
    - if: matrix.os == 'ubuntu-latest'
      name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
        opam-depext-flags: tsdl,conf-pkg-config,conf-alsa
    - if: matrix.os == 'macOS-latest'
      name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
        opam-depext-flags: tsdl
    - run: opam pin /tmp/llama.tar.gz
