name: test
on:
  push:
    branches:
    - '*'
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.1
        opam-pin: false
        opam-depext: false
    - uses: actions/checkout@v3
    - run: opam switch create . --no-install
    - run: opam install -y dune ocamlformat
    - run: opam exec -- dune fmt

  build-and-run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [ 5.1.0, 5.3.0 ]
    steps:
    - uses: actions/checkout@v3
    - if: matrix.os == 'ubuntu-latest'
      name: 'Run "apt update" so setup-ocaml can install depexts (ubuntu)'
      run: |
        sudo apt update
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
